package com.serverless.project;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "CustomerFeedback")
public class FeedbackModel implements Serializable {
	
	private String FeedbackID;
	private String Feedback;
	private String FoodItemName;
	private String ResturantName;
	

	public void setFeedbackID(String fid) {
		this.FeedbackID=fid;
	}
	
	@DynamoDBHashKey(attributeName = "FeedbackID")
	@DynamoDBAutoGeneratedKey
	public String getFeedbackID() {
		return FeedbackID;
	}
	
	
	public void setFeedback(String Feedback) {
		this.Feedback=Feedback;
	}
	
	@DynamoDBAttribute
	public String getFoodItemName() {
		return FoodItemName;
	}
	
	
	public void setResturantName(String ResturantName) {
		this.ResturantName=ResturantName;
	}
	
	@DynamoDBAttribute
	public String getResturantName() {
		return ResturantName;
	}
	

	public void setFoodItemName(String FoodItemName) {
		this.FoodItemName=FoodItemName;
	}
	
	@DynamoDBAttribute
	public String getFeedback() {
		return Feedback;
	}
}

